# Project: Assignment 5_1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = "Assignment\ 5.o"
LINKOBJ  = "Assignment 5.o"
LIBS     = -L"E:/Programing/Dev-Cpp/MinGW64/lib" -L"E:/Programing/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/Programing/Dev-Cpp/MinGW64/include" -I"E:/Programing/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programing/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Programing/Dev-Cpp/MinGW64/include" -I"E:/Programing/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programing/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Programing/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Assignment 5.exe"
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"Assignment\ 5.o": Assignment\ 5.c
	$(CC) -c "Assignment 5.c" -o "Assignment 5.o" $(CFLAGS)
