# Project: Ass6_Home
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o ass6.o menu.o
LINKOBJ  = main.o ass6.o menu.o
LIBS     = -L"E:/Programing/Dev-Cpp/MinGW64/lib" -L"E:/Programing/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Programing/Dev-Cpp/MinGW64/include" -I"E:/Programing/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programing/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Programing/Dev-Cpp/MinGW64/include" -I"E:/Programing/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programing/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Programing/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Ass6_Home.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

ass6.o: ass6.c
	$(CC) -c ass6.c -o ass6.o $(CFLAGS)

menu.o: menu.c
	$(CC) -c menu.c -o menu.o $(CFLAGS)
